//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  event: Event;
  eventConnection: EventConnection;
  post: Post;
  postConnection: PostConnection;
  albums: Albums;
  albumsConnection: AlbumsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};


export type QueryAlbumsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAlbumsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AlbumsFilter>;
};

export type DocumentFilter = {
  event?: InputMaybe<EventFilter>;
  post?: InputMaybe<PostFilter>;
  albums?: InputMaybe<AlbumsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Event | Post | Albums | Folder;

export type Event = Node & Document & {
  __typename?: 'Event';
  title: Scalars['String']['output'];
  eventImage?: Maybe<Scalars['String']['output']>;
  eventImageUrl?: Maybe<Scalars['String']['output']>;
  description: Scalars['String']['output'];
  body: Scalars['JSON']['output'];
  eventDatetime: Scalars['String']['output'];
  eventEndDatetime: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type EventFilter = {
  title?: InputMaybe<StringFilter>;
  eventImage?: InputMaybe<ImageFilter>;
  eventImageUrl?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  eventDatetime?: InputMaybe<DatetimeFilter>;
  eventEndDatetime?: InputMaybe<DatetimeFilter>;
};

export type EventConnectionEdges = {
  __typename?: 'EventConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event>;
};

export type EventConnection = Connection & {
  __typename?: 'EventConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventConnectionEdges>>>;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  video?: Maybe<Scalars['String']['output']>;
  postImage?: Maybe<Scalars['String']['output']>;
  body: Scalars['JSON']['output'];
  tags: Array<Scalars['String']['output']>;
  pubDatetime?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostBodyImageImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  size?: InputMaybe<BooleanFilter>;
};

export type PostBodyImageFilter = {
  image?: InputMaybe<PostBodyImageImageFilter>;
};

export type PostBodyFilter = {
  Image?: InputMaybe<PostBodyImageFilter>;
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  video?: InputMaybe<StringFilter>;
  postImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<PostBodyFilter>;
  tags?: InputMaybe<StringFilter>;
  pubDatetime?: InputMaybe<DatetimeFilter>;
  featured?: InputMaybe<BooleanFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type AlbumsImages = {
  __typename?: 'AlbumsImages';
  image: Scalars['String']['output'];
  alt?: Maybe<Scalars['String']['output']>;
};

export type Albums = Node & Document & {
  __typename?: 'Albums';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  cover?: Maybe<Scalars['String']['output']>;
  images: Array<AlbumsImages>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AlbumsImagesFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type AlbumsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cover?: InputMaybe<ImageFilter>;
  images?: InputMaybe<AlbumsImagesFilter>;
};

export type AlbumsConnectionEdges = {
  __typename?: 'AlbumsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Albums>;
};

export type AlbumsConnection = Connection & {
  __typename?: 'AlbumsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AlbumsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateEvent: Event;
  createEvent: Event;
  updatePost: Post;
  createPost: Post;
  updateAlbums: Albums;
  createAlbums: Albums;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationCreateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationUpdateAlbumsArgs = {
  relativePath: Scalars['String']['input'];
  params: AlbumsMutation;
};


export type MutationCreateAlbumsArgs = {
  relativePath: Scalars['String']['input'];
  params: AlbumsMutation;
};

export type DocumentUpdateMutation = {
  event?: InputMaybe<EventMutation>;
  post?: InputMaybe<PostMutation>;
  albums?: InputMaybe<AlbumsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  event?: InputMaybe<EventMutation>;
  post?: InputMaybe<PostMutation>;
  albums?: InputMaybe<AlbumsMutation>;
};

export type EventMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  eventImage?: InputMaybe<Scalars['String']['input']>;
  eventImageUrl?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  eventDatetime?: InputMaybe<Scalars['String']['input']>;
  eventEndDatetime?: InputMaybe<Scalars['String']['input']>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  video?: InputMaybe<Scalars['String']['input']>;
  postImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  pubDatetime?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AlbumsImagesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type AlbumsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<AlbumsImagesMutation>>>;
};

export type EventPartsFragment = { __typename: 'Event', title: string, eventImage?: string | null, eventImageUrl?: string | null, description: string, body: any, eventDatetime: string, eventEndDatetime: string };

export type PostPartsFragment = { __typename: 'Post', title: string, description: string, video?: string | null, postImage?: string | null, body: any, tags: Array<string>, pubDatetime?: string | null, featured?: boolean | null };

export type AlbumsPartsFragment = { __typename: 'Albums', title: string, description?: string | null, cover?: string | null, images: Array<{ __typename: 'AlbumsImages', image: string, alt?: string | null }> };

export type EventQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventQuery = { __typename?: 'Query', event: { __typename: 'Event', id: string, title: string, eventImage?: string | null, eventImageUrl?: string | null, description: string, body: any, eventDatetime: string, eventEndDatetime: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
}>;


export type EventConnectionQuery = { __typename?: 'Query', eventConnection: { __typename?: 'EventConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventConnectionEdges', cursor: string, node?: { __typename: 'Event', id: string, title: string, eventImage?: string | null, eventImageUrl?: string | null, description: string, body: any, eventDatetime: string, eventEndDatetime: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, description: string, video?: string | null, postImage?: string | null, body: any, tags: Array<string>, pubDatetime?: string | null, featured?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, description: string, video?: string | null, postImage?: string | null, body: any, tags: Array<string>, pubDatetime?: string | null, featured?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AlbumsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AlbumsQuery = { __typename?: 'Query', albums: { __typename: 'Albums', id: string, title: string, description?: string | null, cover?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images: Array<{ __typename: 'AlbumsImages', image: string, alt?: string | null }> } };

export type AlbumsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AlbumsFilter>;
}>;


export type AlbumsConnectionQuery = { __typename?: 'Query', albumsConnection: { __typename?: 'AlbumsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AlbumsConnectionEdges', cursor: string, node?: { __typename: 'Albums', id: string, title: string, description?: string | null, cover?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images: Array<{ __typename: 'AlbumsImages', image: string, alt?: string | null }> } | null } | null> | null } };

export const EventPartsFragmentDoc = gql`
    fragment EventParts on Event {
  __typename
  title
  eventImage
  eventImageUrl
  description
  body
  eventDatetime
  eventEndDatetime
}
    `;
export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  description
  video
  postImage
  body
  tags
  pubDatetime
  featured
}
    `;
export const AlbumsPartsFragmentDoc = gql`
    fragment AlbumsParts on Albums {
  __typename
  title
  description
  cover
  images {
    __typename
    image
    alt
  }
}
    `;
export const EventDocument = gql`
    query event($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventParts
  }
}
    ${EventPartsFragmentDoc}`;
export const EventConnectionDocument = gql`
    query eventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventFilter) {
  eventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventParts
      }
    }
  }
}
    ${EventPartsFragmentDoc}`;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export const AlbumsDocument = gql`
    query albums($relativePath: String!) {
  albums(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AlbumsParts
  }
}
    ${AlbumsPartsFragmentDoc}`;
export const AlbumsConnectionDocument = gql`
    query albumsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AlbumsFilter) {
  albumsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AlbumsParts
      }
    }
  }
}
    ${AlbumsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      event(variables: EventQueryVariables, options?: C): Promise<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}> {
        return requester<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}, EventQueryVariables>(EventDocument, variables, options);
      },
    eventConnection(variables?: EventConnectionQueryVariables, options?: C): Promise<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}> {
        return requester<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}, EventConnectionQueryVariables>(EventConnectionDocument, variables, options);
      },
    post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      },
    albums(variables: AlbumsQueryVariables, options?: C): Promise<{data: AlbumsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AlbumsQueryVariables, query: string}> {
        return requester<{data: AlbumsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AlbumsQueryVariables, query: string}, AlbumsQueryVariables>(AlbumsDocument, variables, options);
      },
    albumsConnection(variables?: AlbumsConnectionQueryVariables, options?: C): Promise<{data: AlbumsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AlbumsConnectionQueryVariables, query: string}> {
        return requester<{data: AlbumsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AlbumsConnectionQueryVariables, query: string}, AlbumsConnectionQueryVariables>(AlbumsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  